[package]
name = "env-lane-plugin-vault"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
env-lane-core = { path = "../env-lane-core" }
env-lane-cli = { path = "../env-lane-cli" }
env-lane-vault = { path = "../env-lane-vault" }
env-lane-plugin-api = { path = "../env-lane-plugin-api" }
clap = { version = "4.5", features = ["derive"] }
serde.workspace = true
serde_json.workspace = true
crossterm = "0.29"

[lints]
workspace = true

[[bin]]
name = "env-lane-plugin-vault"
path = "src/main.rs"
